databases:
  - name: django-boards-db
    plan: basic-256mb
    region: virginia
    databaseName: django_boards_db
    user: django_boards_db_user

services:
  - type: web
    plan: starter
    region: virginia
    name: django-boards
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn django_boards.wsgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-boards-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4