# Generated by Django 5.1.2 on 2024-12-02 09:27

import utils.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', storage=utils.storage_backends.PublicMediaStorage(), upload_to='_profile_avatar_upload_path'),
        ),
    ]
