# Generated by Django 5.1.3 on 2024-12-02 19:24

import utils.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', storage=utils.storage_backends.PublicMediaStorage(), upload_to='./'),
        ),
    ]
