# Generated by Django 5.1 on 2024-09-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post_post_liked_topic_topic_liked_postlike_topiclike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='topic_liked',
        ),
        migrations.DeleteModel(
            name='TopicLike',
        ),
    ]
