# Generated by Django 5.1 on 2024-09-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_topic_topic_liked_delete_topiclike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='post_like_value',
            field=models.CharField(choices=[('♥️', '♥️'), ('♡', '♡')], default='♥️', max_length=2),
        ),
    ]
