# Generated by Django 5.1 on 2024-09-08 10:54

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_postlike_post_like_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='post_like_value',
            field=models.CharField(choices=[('♥️', '♥️'), ('♡', '♡')], default='♥️', max_length=2, verbose_name=boards.models.Post),
        ),
    ]
