# Generated by Django 5.1 on 2024-09-08 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_postlike_post_like_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_liked',
        ),
        migrations.AddField(
            model_name='post',
            name='post_liked_by',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
