# Generated by Django 5.1.4 on 2025-01-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQS',
            new_name='FAQ',
        ),
    ]
