# Generated by Django 5.1.4 on 2025-01-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_rename_faqs_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
